exports.regexpList = [
  /burgers?/i,
  /pizzas?/i,
  /hot dogs?/i,
  /beer/i,
  /sushi/i,
  /drinks/i,
  /food/i,
  /snacks?/i,
  /burgers?/i,
  /sangrias?/i,
  /potluck/i,
  /wines?/i,
  /coffee/i,
  /donuts?/i,
  /pastr(y|ies)/i,
  /refreshments?/i,
  /cookies?/i,
];